spring:
  redis:
    host: localhost
    port: 6379
  ## DB
  datasource:
#    url: jdbc:mariadb://xxxx:3306/test?characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: xxxx
#    password: xxxx
    ## mysql
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: jkmjyy
#    hikari:
#      max-lifetime: 30000
#      connectionInitSql: select 1 from dual
  ## JPA
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#        dialect: org.hibernate.dialect.MariaDB103Dialect
    generate-ddl: true

  ## Swagger Ui
#  springdoc:
#    default-consumes-media-type: application/json
#    default-produces-media-type: application/json
#    swagger-ui:
#      disable-swagger-default-url: true
#      display-query-params-without-oauth2: true

logging:
  level:
    org:
      hibernate:
        SQL : debug

## JWT
jwt:
  ## echo 'jsh-springboot-and-jwt-tutorial-this-is-for-generating-jwt-secretkey-base64'|base64
  secret-key: anNoLXNwcmluZ2Jvb3QtYW5kLWp3dC10dXRvcmlhbC10aGlzLWlzLWZvci1nZW5lcmF0aW5nLWp3dC1zZWNyZXRrZXktYmFzZTY0Cg==
  # 5 minutes duration by default: 30 minutes * 60 seconds * 1000 miliseconds
  access-token-lifetime-in-seconds: 1800 #1800
  # 60 * 60 * 24 * 7 * 1000 : 7day
  refresh-token-lifetime-in-seconds: 604800 #604800

default-images:
  profile: https://mvp.microsoft.com/ko-kr/PublicProfile/Photo/5000853
cloud:
  aws:
    prefix: xxxx
    region:
      static: xxxx
    credentials:
      accessKey: xxxx
      secretkey: xxxx
    s3:
      bucket: xxxx

