name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Setup MySQL
      uses: getong/mariadb-action@v1.1
      with:
        character set server: 'utf8'
        mysql database: ${{ secrets.DB_DATABASE }}
        mysql user: ${{ secrets.DB_USER }}
        mysql password: ${{ secrets.DB_PASSWORD }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Docker build
      run: |
       docker login -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
       docker build -t spring-cicd .
       docker tag spring-cicd ${{ secrets.USERNAME }}/spring-cicd
       docker push ${{ secrets.USERNAME }}/spring-cicd
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.PRIVATE_KEY }}
        envs: GITHUB_SHA
        script: |
          docker pull ${{ secrets.USERNAME }}/spring-cicd
          docker tag ${{ secrets.USERNAME }}/spring-cicd spring-cicd
          docker stop server
          docker run -d --rm --name server -p 80:8080 spring-cicd
